version: '3.8'

services:
  gaia-mcp-sse:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${MCP_SERVER_SSE_PORT:-3000}:${MCP_SERVER_SSE_PORT:-3000}"
    environment:
      - MCP_SERVER_SSE_PORT=${MCP_SERVER_SSE_PORT:-3000}
      - GAIA_API_URL=${GAIA_API_URL:-https://artventure-api.sipher.gg}
      # Redis configuration - Either REDIS_URL or individual components will be used
      # If both are provided, REDIS_URL takes precedence
      - REDIS_URL=${REDIS_URL:-}
      - REDIS_HOST=${REDIS_HOST:-}
      - REDIS_PORT=${REDIS_PORT:-}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - REDIS_KEY_PREFIX=${REDIS_KEY_PREFIX:-gaia-mcp:sessions:}
      # AWS configuration for SSM parameter resolution
      - AWS_REGION=${AWS_REGION:-ap-southeast-1}
      # AWS_PROFILE is only used for local development
      - AWS_PROFILE=${AWS_PROFILE:-}
    restart: unless-stopped
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "${REDIS_PORT:-6379}:${REDIS_PORT:-6379}"
    command: redis-server --appendonly yes
    volumes:
      - ./.data/redis:/data
